-- ═══════════════════════════════════════════════════════════
-- Gold Layer dbt Models — Generated by Claude dbt Agent
-- Target: Snowflake via External Tables on S3 Delta Lake
-- ═══════════════════════════════════════════════════════════


-- ─── dim_customer (SCD Type 2) ───────────────────────────
-- models/gold/dim_customer.sql

WITH source AS (
    SELECT *
    FROM {{ ref('silver_customer_master') }}
),

mdm_golden AS (
    SELECT *
    FROM {{ ref('mdm_golden_records') }}
),

final AS (
    SELECT
        g.customer_uid,
        g.full_name,
        g.email,
        g.phone,
        g.country,
        g.city,
        s.industry,
        CASE
            WHEN g.source_count >= 3 THEN 'Enterprise'
            WHEN g.source_count = 2 THEN 'Mid-Market'
            ELSE 'SMB'
        END AS segment,
        g.match_score,
        g.source_systems,
        g.created_date,
        g.last_activity_date,
        TRUE AS is_current,
        CURRENT_TIMESTAMP() AS _loaded_at
    FROM mdm_golden g
    LEFT JOIN source s ON g.primary_source_id = s.source_id
)

SELECT * FROM final;


-- ─── dim_product ─────────────────────────────────────────
-- models/gold/dim_product.sql

WITH source AS (
    SELECT *
    FROM {{ ref('silver_product_master') }}
),

final AS (
    SELECT
        product_id,
        product_name,
        category,
        subcategory,
        unit_price,
        cost_price,
        ROUND((unit_price - cost_price) / NULLIF(unit_price, 0) * 100, 1) AS margin_pct,
        CASE
            WHEN category IN ('Software License', 'Cloud Platform', 'Support & Maintenance')
            THEN TRUE ELSE FALSE
        END AS is_recurring,
        launch_date,
        is_active,
        CURRENT_TIMESTAMP() AS _loaded_at
    FROM source
    WHERE is_active = TRUE
)

SELECT * FROM final;


-- ─── fact_sales ──────────────────────────────────────────
-- models/gold/fact_sales.sql

WITH orders AS (
    SELECT *
    FROM {{ ref('silver_orders') }}
),

customers AS (
    SELECT customer_uid, source_id
    FROM {{ ref('dim_customer') }}
    WHERE is_current = TRUE
),

final AS (
    SELECT
        o.order_id,
        c.customer_uid,
        o.product_id,
        o.order_date,
        o.quantity,
        o.unit_price,
        o.discount_pct,
        ROUND(o.quantity * o.unit_price * (1 - o.discount_pct / 100.0), 2) AS line_total,
        ROUND(o.quantity * p.cost_price, 2) AS cost_total,
        ROUND(o.quantity * o.unit_price * (1 - o.discount_pct / 100.0) - o.quantity * p.cost_price, 2) AS profit,
        o.order_source,
        o.sales_rep,
        CURRENT_TIMESTAMP() AS _loaded_at
    FROM orders o
    INNER JOIN customers c ON o.source_customer_id = c.source_id
    INNER JOIN {{ ref('dim_product') }} p ON o.product_id = p.product_id
)

SELECT * FROM final;


-- ─── Snowflake External Table Setup ─────────────────────
-- sql/snowflake_setup.sql

CREATE OR REPLACE STORAGE INTEGRATION s3_lakehouse_int
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = 'arn:aws:iam::role/snowflake-lakehouse-role'
    STORAGE_ALLOWED_LOCATIONS = ('s3://company-mdm-lakehouse-prod/gold/');

CREATE OR REPLACE STAGE gold_stage
    STORAGE_INTEGRATION = s3_lakehouse_int
    URL = 's3://company-mdm-lakehouse-prod/gold/'
    FILE_FORMAT = (TYPE = PARQUET);

CREATE OR REPLACE EXTERNAL TABLE dim_customer_ext (
    customer_uid VARCHAR AS (VALUE:customer_uid::VARCHAR),
    full_name    VARCHAR AS (VALUE:full_name::VARCHAR),
    email        VARCHAR AS (VALUE:email::VARCHAR),
    country      VARCHAR AS (VALUE:country::VARCHAR),
    segment      VARCHAR AS (VALUE:segment::VARCHAR),
    status       VARCHAR AS (VALUE:status::VARCHAR),
    lifetime_value NUMBER(18,2) AS (VALUE:lifetime_value::NUMBER(18,2))
)
LOCATION = @gold_stage/dim_customer/
AUTO_REFRESH = TRUE
FILE_FORMAT = (TYPE = PARQUET);

-- Materialized View for Customer 360
CREATE OR REPLACE MATERIALIZED VIEW mv_customer_360 AS
SELECT
    c.customer_uid,
    c.full_name,
    c.segment,
    c.status,
    c.country,
    COUNT(DISTINCT s.order_id) AS total_orders,
    SUM(s.line_total) AS total_revenue,
    AVG(s.line_total) AS avg_order_value,
    COUNT(DISTINCT i.interaction_id) AS total_interactions,
    MAX(s.order_date) AS last_order_date
FROM dim_customer_ext c
LEFT JOIN fact_sales_ext s ON c.customer_uid = s.customer_uid
LEFT JOIN fact_interactions_ext i ON c.customer_uid = i.customer_uid
GROUP BY 1, 2, 3, 4, 5;
